In [2]:
import numpy as np
from numpy import matmul as mm

In [28]:
theta1 = 0
theta2 = -0.52359878
theta3 = 2.0943951

l1 = 0
we = 0.11651167932822327
h1 = 0
de = 0

l2 = 0.05149697649731044
l3 = 0.07238155732083357
le = 0.11651167932822327
phi = np.radians(0)

In [29]:
R01 = np.array([[np.cos(theta1+phi),-np.sin(theta1+phi),0],[np.sin(theta1+phi),np.cos(theta1+phi),0],[0,0,1]])
T01 = np.array([[l1*np.cos(phi)],[l1*np.sin(phi)],[h1]])

R12 = np.array([[1,0,0],[0,np.cos(theta2),-np.sin(theta2)],[0,np.sin(theta2),np.cos(theta2)]])
T12 = np.array([[0],[-l2],[0]])

R23 = np.array([[1,0,0],[0,np.cos(-theta3),-np.sin(theta3)],[0,np.sin(-theta3),np.cos(-theta3)]])
T23 = np.array([[0],[-l3],[0]])

R3e = np.array([[1,0,0],[0,0,-1],[0,1,0]])
T3e = np.array([[0],[-le],[de]])

In [30]:
M01 = np.array([[np.cos(theta1+phi),-np.sin(theta1+phi),0,l1*np.cos(phi)],\
                [np.sin(theta1+phi),np.cos(theta1+phi),0,l1*np.sin(phi)],\
                [0,0,1,h1],\
                [0,0,0,1]])

M12 = np.array([[1,0,0,0],\
                [0,np.cos(theta2),-np.sin(theta2),-l2],\
                [0,np.sin(theta2),np.cos(theta2),0],\
                [0,0,0,1]])

M23 = np.array([[1,0,0,0],\
                [0,np.cos(-theta3),-np.sin(theta3),l3],\
                [0,np.sin(-theta3),np.cos(-theta3),0],\
                [0,0,0,1]])

M3e = np.array([[1,0,0,0],\
                [0,0,-1,-le],\
                [0,1,0,de],\
                [0,0,0,1]])

In [31]:
T01

array([[0.],
       [0.],
       [0.]])

In [32]:
p = np.array([[0],[0],[0]]) #expect ~[2.2,-2.2,-.7] for [0,0,0] input
p = mm(R3e,p)
print(p)
p = p+T3e
print(p)
p = mm(R23,p)
print(p)
p = p+T23
print(p)
p = mm(R12,p)
print(p)
p = p+T12
print(p)
p = mm(R01,p)
p

[[0]
 [0]
 [0]]
[[ 0.        ]
 [-0.11651168]
 [ 0.        ]]
[[0.        ]
 [0.05825584]
 [0.10090207]]
[[ 0.        ]
 [-0.01412572]
 [ 0.10090207]]
[[0.        ]
 [0.03821781]
 [0.09444662]]
[[ 0.        ]
 [-0.01327917]
 [ 0.09444662]]


array([[ 0.        ],
       [-0.01327917],
       [ 0.09444662]])

0.5