In [1]:
import numpy as np
from numpy import matmul as mm
from numpy import transpose as tp

In [39]:
theta1 = 0
# theta2 = -0.52359878
# theta3 = 2.0943951
theta2 = 0
theta3 = -np.pi/2

# l1 = 0
# we = 0.11651167932822327
# h1 = 0
# de = 0
# l2 = 0.05149697649731044
# l3 = 0.07238155732083357
# le = 0.11651167932822327

Y1 = 0
Y2 = 0.05149697649731044
Y3 = 0.07238155732083357
Y4 = 0.11651167932822327
Z4 = 0



phi = np.radians(0)

In [40]:
def skewer_me(www):
    return np.array([[0,-www[2],www[1]],[www[2],0,-www[1]],[-www[1],www[0],0]])

def erot_wq(w,q,theta):
    n = w.shape[1]
    
    #get yo vees
    v = np.zeros(w.shape)
    erots = np.zeros([n,4,4])
    print(erots)
    for i in range(n):
        v[:,i] = np.cross(w[:,i],q[:,i])
        wsk = skewer_me(w[:,i])
        ewt = np.eye(3)+np.sin(theta[i])*wsk+(1-np.cos(theta[i]))*wsk**2
        print(ewt)
        other = (np.eye(3)*theta[i]+(1-np.cos(theta[i]))*wsk+(theta[i]-np.sin(theta[i]))*wsk**2)
        erots[i,:3,:] = np.hstack((ewt,np.reshape(mm(other,v[:,i]),[3,1])))
        erots[i,3,3] = 1
    return erots

In [41]:
omega = np.array([[0 , np.cos(phi) , np.cos(phi)],\
                  [0 , np.sin(phi) , np.sin(phi)],\
                  [1,0,0]])
q = np.array([[ Y1*np.sin(phi) ,  Y2*np.sin(phi) ,  Y3*np.sin(phi)],\
              [-Y1*np.cos(phi) , -Y2*np.cos(phi) , -Y3*np.cos(phi)],\
              [0,0,0]])
ttt = mm(q,np.ones(3))+np.array([Y4*np.sin(phi),-Y4*np.cos(phi),Z4])

M = np.array([[np.cos(phi) , -np.sin(phi) , 0 , ttt[0]],\
              [np.sin(phi) , np.cos(phi) , 0 , ttt[1]],\
              [0,0,1,ttt[2]],\
              [0,0,0,1]])
# thetas = [0,0,0]

In [42]:
thetas = [theta1,theta2,theta3]
ET = erot_wq(omega,q,thetas)
ET

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[ 1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00 -1.11022302e-16  1.00000000e+00]]


array([[[ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00],
        [ 0.00000000e+00,  1.00000000e+00,  0.00000000e+00,
          0.00000000e+00],
        [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00,
          0.00000000e+00],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          1.00000000e+00]],

       [[ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00],
        [ 0.00000000e+00,  1.00000000e+00,  0.00000000e+00,
          0.00000000e+00],
        [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00,
          0.00000000e+00],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          1.00000000e+00]],

       [[ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00],
        [ 0.00000000e+00,  1.00000000e+00,  0.00000000e+00,
          0.00000000e+00],
        [ 0.00000000e+00, -1.11022302e-16,  1.00000000e+00,
          1.13696684e-01],
        [ 0.00000000e+00,  0.00000000e+

In [43]:
bigT = mm(ET[0,:,:],mm(ET[1,:,:],mm(ET[2,:,:],M)))

In [44]:
mm(bigT,np.array([0,0,0,1]))

array([ 0.        , -0.24039021,  0.11369668,  1.        ])

In [24]:
a = np.array([[1,1,1,1],[2,2,2,2],[3,4,5,6]])
b = np.array([9,9,9])
print(b)
b = np.reshape(b,[3,1])
print(b)
d = np.hstack((a,b))
print(d)
c = np.array([9,9,9,9,9])

[9 9 9]
[[9]
 [9]
 [9]]
[[1 1 1 1 9]
 [2 2 2 2 9]
 [3 4 5 6 9]]
