In [2]:
import vrep
import time
import numpy as np
from math import cos, sin
from scipy.linalg import expm,logm
from copy import copy as copy
import hex_helper as hh
import step_3 as ss

In [4]:
# ======================================================================================================= #
# ======================================= Start Simulation ============================================== #
# ======================================================================================================= #

# Close all open connections (Clear bad cache)
vrep.simxFinish(-1)
# Connect to V-REP (raise exception on failure)
clientID = vrep.simxStart('127.0.0.1', 19997, True, True, 5000, 5)
if clientID == -1:
	raise Exception('Failed connecting to remote API server')

print(clientID)
# ======================================== Setup "handle"  =========================================== #
handles, body_handles = hh.init_handles(clientID)

0
[[17, 19, 21], [28, 30, 32], [38, 40, 42], [48, 50, 52], [58, 60, 62], [68, 70, 72]] [24, 35, 45, 55, 65, 75, 27]


In [6]:
# Close all open connections (Clear bad cache)
vrep.simxFinish(-1)
# Connect to V-REP (raise exception on failure)
clientID = vrep.simxStart('127.0.0.1', 19997, True, True, 5000, 5)
if clientID == -1:
	raise Exception('Failed connecting to remote API server')

# Start simulation
vrep.simxStartSimulation(clientID, vrep.simx_opmode_oneshot)

# ******************************** Your robot control code goes here  ******************************** #
print(hh.get_joint(handles, body_handles,clientID))
time.sleep(4)

vrep.simxSetJointTargetPosition(clientID, handles[0][0], np.radians(0), vrep.simx_opmode_oneshot)
vrep.simxSetJointTargetPosition(clientID, handles[0][1], np.radians(0), vrep.simx_opmode_oneshot)
vrep.simxSetJointTargetPosition(clientID, handles[0][2], np.radians(0), vrep.simx_opmode_oneshot)
print(hh.get_joint(handles, body_handles,clientID))

time.sleep(10)


# Stop simulation
vrep.simxStopSimulation(clientID, vrep.simx_opmode_oneshot)
# Before closing the connection to V-REP, make sure that the last command sent out had time to arrive. You can guarantee this with (for example):
vrep.simxGetPingTime(clientID)
# Close the connection to V-REP
vrep.simxFinish(clientID)
print("==================== ** Simulation Ended ** ====================")

# ======================================================================================================= #
# ======================================== End Simulation =============================================== #
# ======================================================================================================= #

([0.08000001311302185, 0.13013768196105957, 0.2012782096862793, 0.3124360740184784], [-2.7939677238464355e-09, 0.0035504773259162903, 0.018231209367513657, 0.053879134356975555], [0.003102332353591919, -0.008100681006908417, -0.008094392716884613, 0.002968795597553253])
([0.08000007271766663, 0.12840953469276428, 0.20033866167068481, 0.31702038645744324], [-2.0489096641540527e-08, 0.013532735407352448, 0.023650506511330605, 0.027501530945301056], [0.003102324903011322, -0.008099086582660675, -0.008099228143692017, 0.0029528960585594177])
==================== ** Simulation Ended ** ====================


In [3]:
a1 = np.array([0.07999998331069946, 0.000000007450580596,  0.003102332353591919])
a2 = np.array([0.12840536236763555, 0.013532258570194244, -0.008097179234027863])
a3 = np.array([0.19271773099899292, 0.022167865186929703,  0.02452348917722702])
a4 = np.array([0.22692781686782837, 0.017045358195900917, -0.09304545819759369])

l2 = (a2-a1)
print(l2)
l3 = (a3-a2)
print(l3)
le = (a4-a3)
print(le)

[ 0.05026454  0.         -0.01119888]
[0.06268057 0.         0.03619718]
[ 0.01107928  0.         -0.11598371]
