In [17]:
import numpy as np
from numpy import matmul as mm
from numpy import transpose as tp
from scipy import linalg 

SyntaxError: invalid syntax (<ipython-input-17-e73b424d0597>, line 4)

In [73]:
theta1 = np.radians(0)
theta2 = np.radians(-30)
theta3 = np.radians(120)

theta=[theta1,theta2,theta3]

Y1 = 0
Y2 = 0.05149697649731044
Y3 = 0.07238155732083357
Y4 = 0.11651167932822327
Z4 = 0

phi = np.radians(0)

In [74]:
w1 = np.array([0,0,1])
q1 = np.array([Y1*np.sin(phi),-Y1*np.cos(phi),0])
v1 = np.cross(-w1,q1)
v1

array([ 0., -0.,  0.])

In [75]:
w2 = np.array([np.cos(phi),np.sin(phi),0])
q2 = np.array([Y2*np.sin(phi),-Y2*np.cos(phi),0])+q1
v2 = np.cross(-w2,q2)
q2

array([ 0.        , -0.05149698,  0.        ])

In [76]:
w3 = np.array([np.cos(phi),np.sin(phi),0])
q3 = np.array([Y3*np.sin(phi),-Y3*np.cos(phi),0])+q2
v3 = np.cross(-w3,q3)
q3

array([ 0.        , -0.12387853,  0.        ])

In [77]:
S_mat1 = np.array([[     0,-w1[2], w1[1],v1[0]],\
                   [ w1[2],     0,-w1[0],v1[1]],\
                   [-w1[1], w1[0],     0,v1[2]],\
                   [     0,     0,     0,    0]])
S_mat1

array([[ 0., -1.,  0.,  0.],
       [ 1.,  0.,  0., -0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [78]:
S_mat2 = np.array([[     0,-w2[2], w2[1],v2[0]],\
                   [ w2[2],     0,-w2[0],v2[1]],\
                   [-w2[1], w2[0],     0,v2[2]],\
                   [     0,     0,     0,    0]])
S_mat2

array([[ 0.        , -0.        ,  0.        , -0.        ],
       [ 0.        ,  0.        , -1.        ,  0.        ],
       [-0.        ,  1.        ,  0.        ,  0.05149698],
       [ 0.        ,  0.        ,  0.        ,  0.        ]])

In [79]:
S_mat3 = np.array([[     0,-w3[2], w3[1],v3[0]],\
                   [ w3[2],     0,-w3[0],v3[1]],\
                   [-w3[1], w3[0],     0,v3[2]],\
                   [     0,     0,     0,    0]])
S_mat3

array([[ 0.        , -0.        ,  0.        , -0.        ],
       [ 0.        ,  0.        , -1.        ,  0.        ],
       [-0.        ,  1.        ,  0.        ,  0.12387853],
       [ 0.        ,  0.        ,  0.        ,  0.        ]])

In [80]:
q4 = np.array([Y4*np.sin(phi),-Y4*np.cos(phi),0])+q3
M = np.array([[1,0,0,q4[0]],\
              [0,1,0,q4[1]],\
              [0,0,1,q4[2]],\
              [0,0,0,1]])
M

array([[ 1.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  1.        ,  0.        , -0.24039021],
       [ 0.        ,  0.        ,  1.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [81]:
T1 = linalg.expm(S_mat1*theta[0])
T1

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [82]:
T2 = linalg.expm(S_mat2*theta[1])
T2

array([[ 1.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.8660254 ,  0.5       , -0.00689929],
       [ 0.        , -0.5       ,  0.8660254 , -0.02574849],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [83]:
T3 = linalg.expm(S_mat3*theta[2])
T3

array([[ 1.        ,  0.        ,  0.        ,  0.        ],
       [-0.        , -0.5       , -0.8660254 , -0.1858178 ],
       [ 0.        ,  0.8660254 , -0.5       ,  0.10728196],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [84]:
T = mm(T1,mm(T2,mm(T3,M)))
T[:,3]

array([ 0.        , -0.11418124, -0.0803209 ,  1.        ])